package com.careerblueprint.service;

import com.careerblueprint.model.DailyMission;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import java.util.HashMap;
import java.util.Map;

@Service
public class MissionService {
    private Map<Integer, DailyMission> missionMap = new HashMap<>();

    @PostConstruct
    public void initMissions() {
        // FASE 1: THE DEEP CLEANING (HARI 1-30) - Berdamai dengan Luka & Trauma
        missionMap.put(1, new DailyMission(1, "DEEP CLEANING", "Surat untuk Masa Lalu", "Tuliskan satu kejadian di mana kamu merasa paling kerdil. Akui rasanya, lalu tuliskan bahwa kamu memaafkan dirimu yang saat itu tidak berdaya.", "Tulis surat ini di kertas, lalu bakar atau simpan di kotak khusus.", "Self-Compassion +1", "Kamu tidak bisa melangkah maju jika masih menatap ke belakang."));
        missionMap.put(2, new DailyMission(2, "DEEP CLEANING", "Audit Lingkungan Digital", "Hapus atau mute akun sosmed yang memicu rasa minder berlebihan. Bersihkan 'ruang' sebelum membangun.", "Unfollow minimal 5 akun yang bikin Mental Nyam-Nyam muncul.", "Mental Space +1", "Apa yang kamu konsumsi, itu yang akan kamu jadi."));
        missionMap.put(3, new DailyMission(3, "DEEP CLEANING", "Kemenangan Kecil", "Lakukan disiplin fisik (menyapu lantai, merapikan meja, atau mencuci piring) sebagai simbol bahwa kamu memegang kendali atas hidupmu kembali.", "Foto sebelum dan sesudah. Rasakan bedanya.", "Control +1", "Disiplin kecil membangun disiplin besar."));
        missionMap.put(4, new DailyMission(4, "DEEP CLEANING", "Identifikasi Sudut Masjid", "List 3 momen di mana kamu merasa 'dikucilkan' atau tidak dihargai. Jangan hindari. Hadapi.", "Tulis di journal: 'Saya ada di sana karena...' dan temukan pelajaran.", "Courage +1", "Sudut Masjid bukan akhir, itu adalah tempat untuk berdoa."));
        missionMap.put(5, new DailyMission(5, "DEEP CLEANING", "Layangan Putus Audit", "Identifikasi 1 mimpi atau target yang pernah kamu 'lepaskan' karena merasa tidak layak.", "Tulis: 'Layangan itu putus karena angin, bukan karena bambunya jelek.'", "Hope +1", "Layangan putus bukan berarti bambunya rusak."));
        missionMap.put(6, new DailyMission(6, "DEEP CLEANING", "Konfrontasi Mental Nyam-Nyam", "Tulis 3 kalimat negatif yang sering muncul di kepalamu (misal: 'Gue nggak bisa', 'Gue cuma figuran').", "Untuk setiap kalimat, tulis counter-argument dengan bukti nyata.", "Mental Strength +1", "Mental Nyam-Nyam hanya nyamuk. Bisa ditepuk."));
        missionMap.put(7, new DailyMission(7, "DEEP CLEANING", "Hari Tenang", "Hari ini tidak ada tugas berat. Hanya istirahat dan refleksi.", "Duduk diam 30 menit tanpa HP. Hanya kamu dan pikiranmu.", "Peace +5", "Kamu berhak istirahat. Perjuangan baru dimulai.", "BONUS_DAY"));
        missionMap.put(8, new DailyMission(8, "DEEP CLEANING", "Raut Bambu Pertama", "Pilih 1 skill yang kamu punya tapi selalu kamu anggap 'sampah' atau 'nggak penting'.", "Tulis 3 cara skill itu bisa berguna untuk orang lain.", "Perspective +1", "Bambu yang diraut dengan benar bisa terbang tinggi."));
        missionMap.put(9, new DailyMission(9, "DEEP CLEANING", "Detox Kritik Diri", "Selama 24 jam, setiap kali kamu mau mengkritik diri sendiri, tahan. Ganti dengan 1 hal yang kamu syukuri.", "Catat di HP: setiap kali berhasil menahan kritik, kasih tanda.", "Self-Love +1", "Kritik diri yang berlebihan adalah bentuk bullying terhadap diri sendiri."));
        missionMap.put(10, new DailyMission(10, "DEEP CLEANING", "Audit Lingkungan Fisik", "Lihat sekitarmu. Apakah ada benda yang mengingatkanmu pada kegagalan atau rasa malu?", "Buang, simpan di laci tersembunyi, atau ubah maknanya.", "Environment +1", "Lingkungan yang bersih = pikiran yang bersih."));
        missionMap.put(11, new DailyMission(11, "DEEP CLEANING", "Mengakui Kelemahan", "Tulis 3 kelemahanmu yang selalu kamu sembunyikan. Jangan malu. Akui.", "Share ke 1 orang yang kamu percaya (atau simpan di journal).", "Vulnerability +1", "Kelemahan yang diakui adalah awal kekuatan."));
        missionMap.put(12, new DailyMission(12, "DEEP CLEANING", "Batasan (Boundary) Pertama", "Identifikasi 1 situasi di mana kamu selalu 'yes man' padahal ingin bilang 'tidak'.", "Hari ini, coba bilang 'tidak' untuk 1 request yang tidak sesuai prioritas.", "Boundary +1", "Setiap 'ya' adalah 'tidak' untuk diri sendiri."));
        missionMap.put(13, new DailyMission(13, "DEEP CLEANING", "Menggali 'Kenapa'", "Untuk setiap ketakutanmu (takut gagal, takut diremehkan), tanya 'Kenapa?' sampai 5 kali.", "Temukan root cause ketakutanmu.", "Insight +1", "Kenapa yang dalam akan menunjukkan jalan keluar."));
        missionMap.put(14, new DailyMission(14, "DEEP CLEANING", "Validasi Diri", "Tulis 10 hal yang kamu lakukan dengan baik (meskipun kecil). Tanpa membandingkan dengan orang lain.", "Baca list ini setiap kali Mental Nyam-Nyam muncul.", "Validation +1", "Validasi dari diri sendiri lebih kuat dari validasi orang lain."));
        missionMap.put(15, new DailyMission(15, "DEEP CLEANING", "Hari Refleksi", "Hari ini spesial. Tidak ada tugas produktif.", "Pergi ke tempat yang tenang (taman, kafe, atau kamar). Bawa journal. Tulis apa yang kamu rasakan.", "Clarity +5", "15 hari sudah. Kamu sudah mulai membersihkan puing-puing.", "BONUS_DAY"));
        missionMap.put(16, new DailyMission(16, "DEEP CLEANING", "Menghapus 'Seharusnya'", "Identifikasi 3 kalimat 'seharusnya' yang sering muncul (seharusnya sukses, seharusnya kaya, seharusnya...).", "Ganti dengan 'Saya sedang menuju...' atau 'Saya sudah...'", "Acceptance +1", "'Seharusnya' adalah musuh kebahagiaan."));
        missionMap.put(17, new DailyMission(17, "DEEP CLEANING", "Audit Relationship", "List 5 orang yang paling sering bersamamu. Apakah mereka memberi energi atau menguras?", "Untuk yang menguras, kurangi interaksi. Untuk yang memberi, apresiasi.", "Relationship +1", "Kamu adalah rata-rata dari 5 orang terdekatmu."));
        missionMap.put(18, new DailyMission(18, "DEEP CLEANING", "Menghadapi Penolakan", "Ingat 1 momen penolakan yang menyakitkan. Tulis ulang ceritanya dari sudut pandang pembelajaran.", "Apa yang kamu pelajari dari penolakan itu?", "Resilience +1", "Penolakan bukan akhir. Itu adalah redireksi."));
        missionMap.put(19, new DailyMission(19, "DEEP CLEANING", "Ritual Pagi Baru", "Buat ritual pagi yang tidak melibatkan HP (meditasi, journaling, olahraga, atau sekadar minum kopi tenang).", "Lakukan ini selama 7 hari ke depan.", "Discipline +1", "Bagaimana kamu memulai hari menentukan bagaimana kamu mengakhiri hari."));
        missionMap.put(20, new DailyMission(20, "DEEP CLEANING", "Mid-Phase Reflection", "Review 20 hari terakhir. Apa yang paling berat? Apa yang paling menyenangkan?", "Tulis 1 hal yang kamu banggakan dari 20 hari ini.", "Awareness +1", "Refleksi tanpa judgment adalah kunci pertumbuhan."));
        missionMap.put(21, new DailyMission(21, "DEEP CLEANING", "Mengganti Narasi", "Identifikasi 1 narasi negatif tentang dirimu (misal: 'Gue cuma orang biasa').", "Tulis narasi baru: 'Gue adalah orang yang...'", "Storytelling +1", "Narasi yang kamu ceritakan tentang dirimu akan menjadi kenyataan."));
        missionMap.put(22, new DailyMission(22, "DEEP CLEANING", "Menghargai Proses", "Tulis 3 proses yang kamu jalani (bukan hasil). Misal: 'Saya sudah belajar coding selama 6 bulan'.", "Apresiasi proses, bukan hanya mengejar hasil.", "Patience +1", "Hasil adalah bonus. Proses adalah kehidupan."));
        missionMap.put(23, new DailyMission(23, "DEEP CLEANING", "Detox Perbandingan", "Selama 24 jam, setiap kali ingin membandingkan diri dengan orang lain, tahan.", "Ganti fokus ke progress diri sendiri.", "Focus +1", "Perbandingan adalah pencuri kebahagiaan."));
        missionMap.put(24, new DailyMission(24, "DEEP CLEANING", "Menghadapi Ketakutan", "Pilih 1 ketakutan terbesarmu. Tulis skenario terburuk yang bisa terjadi.", "Tulis juga skenario terbaik dan rencana jika skenario terburuk terjadi.", "Bravery +1", "Ketakutan yang dihadapi akan kehilangan kekuatannya."));
        missionMap.put(25, new DailyMission(25, "DEEP CLEANING", "Mengidentifikasi Nilai", "List 5 nilai yang paling penting bagimu (kejujuran, kebebasan, keluarga, dll).", "Cek apakah hidupmu saat ini selaras dengan nilai-nilai ini.", "Alignment +1", "Hidup yang tidak selaras dengan nilai adalah hidup yang kosong."));
        missionMap.put(26, new DailyMission(26, "DEEP CLEANING", "Menghapus 'Nanti'", "Identifikasi 3 hal yang selalu kamu bilang 'nanti' tapi tidak pernah dilakukan.", "Pilih 1, lakukan hari ini. Sekarang.", "Action +1", "'Nanti' adalah bahasa penundaan."));
        missionMap.put(27, new DailyMission(27, "DEEP CLEANING", "Mengampuni Orang Lain", "Pilih 1 orang yang pernah menyakitimu. Tulis surat maaf untuk dirimu sendiri (bukan untuk mereka).", "Kamu tidak perlu mengirim surat ini. Cukup tulis dan lepaskan.", "Forgiveness +1", "Mengampuni bukan untuk mereka. Untukmu."));
        missionMap.put(28, new DailyMission(28, "DEEP CLEANING", "Menghadapi Kritik", "Ingat 1 kritik yang menyakitkan. Bedah kritik itu: apa yang benar? apa yang tidak?", "Ambil yang berguna, buang yang tidak.", "Wisdom +1", "Kritik adalah data. Bukan kebenaran mutlak."));
        missionMap.put(29, new DailyMission(29, "DEEP CLEANING", "Persiapan Fase 2", "Review apa yang akan dipelajari di Fase 2. Siapkan mental untuk 'Instalasi'.", "Tulis 1 skill yang ingin kamu 'install' di Fase 2.", "Readiness +1", "Persiapan yang baik adalah setengah kesuksesan."));
        missionMap.put(30, new DailyMission(30, "DEEP CLEANING", "Graduasi Fase 1", "Review seluruh Fase 1. Tulis transformasi yang sudah terjadi.", "Celebrasi: lakukan sesuatu yang kamu sayangi (makan enak, beli sesuatu, atau sekadar senyum).", "Transformation +5", "30 hari Deep Cleaning selesai. Kamu sudah siap untuk instalasi.", "BONUS_DAY"));

        // FASE 2: THE INSTALLATION (HARI 31-60) - Mindset & Skill Synthesis
        missionMap.put(31, new DailyMission(31, "INSTALLATION", "Deconstruct Envy", "Pilih satu orang yang kamu iringi. Bedah 3 skill teknis yang mereka punya. Masukkan ke dalam daftar belajarmu.", "Jangan iri. Jadikan mereka sebagai curriculum.", "Learning +1", "Iri adalah data. Bukan rasa, tapi daftar belanja."));
        missionMap.put(32, new DailyMission(32, "INSTALLATION", "Skill Mixology", "Ambil 3 skill lumayanmu (misal: Menulis, Excel, Masak). Rancang satu identitas baru dari kombinasi ini.", "Tulis: 'Saya adalah orang yang menggabungkan X, Y, dan Z untuk...'", "Creativity +1", "Kombinasi unik = identitas unik."));
        missionMap.put(33, new DailyMission(33, "INSTALLATION", "Blok Waktu 90 Menit", "Latih satu skill teknis secara mendalam tanpa gangguan HP (Deep Work).", "Matikan notifikasi. Fokus 100%.", "Focus +1", "Deep work adalah superpower di era shallow work."));
        missionMap.put(34, new DailyMission(34, "INSTALLATION", "Harta Karun di Puing", "Identifikasi 1 pengalaman 'gagal' atau 'sampah' dari masa lalu. Cari skill yang tersembunyi di sana.", "Contoh: Pernah dipecat? Skill: Resilience, negosiasi, adaptasi.", "Insight +1", "Di antara puing, ada harta karun."));
        missionMap.put(35, new DailyMission(35, "INSTALLATION", "Raut Bambu Kedua", "Ambil skill 'sampah' yang sudah diidentifikasi. Raut (asah) dengan belajar lebih dalam.", "Cari 1 resource (video, artikel, course) tentang skill itu.", "Skill +1", "Bambu yang diraut akan terbang lebih tinggi."));
        missionMap.put(36, new DailyMission(36, "INSTALLATION", "Hari Integrasi", "Hari ini libur dari belajar skill baru. Integrasi apa yang sudah dipelajari.", "Journaling: Bagaimana skill ini mengubah cara kamu melihat diri?", "Integration +5", "Istirahat adalah bagian dari proses.", "BONUS_DAY"));
        missionMap.put(37, new DailyMission(37, "INSTALLATION", "Proof of Mini-Work", "Buat 1 karya kecil menggunakan skill yang sedang diasah (artikel, desain, kode, atau video).", "Share ke 1 orang. Minta feedback.", "Output +1", "Tanpa output, skill hanya hobi."));
        missionMap.put(38, new DailyMission(38, "INSTALLATION", "Mengganti 'Nggak Bisa'", "Identifikasi 1 skill yang kamu bilang 'nggak bisa'. Coba buktikan salah.", "Coba lakukan 1 hal kecil dengan skill itu.", "Courage +1", "'Nggak bisa' adalah kebohongan yang kamu percayai."));
        missionMap.put(39, new DailyMission(39, "INSTALLATION", "Skill Stack Layering", "Tambahkan layer baru ke skill yang sudah ada. Misal: jika bisa coding, tambah skill deployment.", "Buat 1 project yang menunjukkan layering ini.", "Depth +1", "Skill yang dalam lebih berharga dari skill yang luas."));
        missionMap.put(40, new DailyMission(40, "INSTALLATION", "Mid-Phase Check", "Review 10 hari pertama Fase 2. Apakah skill yang dipilih tepat?", "Jika perlu, pivot. Jika tidak, double down.", "Strategy +1", "Pivot bukan failure. Itu optimasi."));
        missionMap.put(41, new DailyMission(41, "INSTALLATION", "Mencari Mentor", "Identifikasi 1 orang yang bisa jadi mentor untuk skill ini (bisa online, bisa offline).", "Follow mereka, baca konten mereka, pelajari pola.", "Direction +1", "Jangan reinvent the wheel. Stand on shoulders of giants."));
        missionMap.put(42, new DailyMission(42, "INSTALLATION", "Output Sprint", "Buat 3 output kecil dalam 1 hari (batching).", "Share semua 3 output ke platform yang berbeda.", "Velocity +1", "Quantity leads to quality."));
        missionMap.put(43, new DailyMission(43, "INSTALLATION", "Menghadapi Kegagalan Belajar", "Ingat 1 kali kamu gagal belajar sesuatu. Analisis: kenapa gagal?", "Buat rencana untuk menghindari kegagalan yang sama.", "Resilience +1", "Kegagalan adalah data, bukan identitas."));
        missionMap.put(44, new DailyMission(44, "INSTALLATION", "Tool Mastery", "Pelajari 1 tool/software yang relevan dengan skill ini sampai bisa pakai tanpa bantuan.", "Buat 1 project menggunakan tool tersebut.", "Technical +1", "Master your tools, master your craft."));
        missionMap.put(45, new DailyMission(45, "INSTALLATION", "Hari Inspirasi", "Hari ini spesial. Tidak ada tugas teknis.", "Baca/watch 1 kisah orang yang berhasil dari skill yang sama.", "Inspiration +5", "45 hari sudah. Setengah jalan.", "BONUS_DAY"));
        missionMap.put(46, new DailyMission(46, "INSTALLATION", "Case Study Deep Dive", "Analisis 1 case study dari expert di skill ini. Bedah strategi mereka.", "Catat 3 actionable insights yang bisa kamu implement.", "Analysis +1", "Case studies adalah shortcut ke pengalaman."));
        missionMap.put(47, new DailyMission(47, "INSTALLATION", "Feedback Brutal", "Share 1 karya dan minta brutal honest feedback. Jangan minta pujian.", "Implement feedback tersebut dalam karya berikutnya.", "Growth +1", "Feedback menyakitkan, tapi menyembuhkan."));
        missionMap.put(48, new DailyMission(48, "INSTALLATION", "Time Blocking Ritual", "Block 2 jam khusus untuk skill development setiap hari. Jadwalkan di calendar.", "Lakukan ini selama 7 hari ke depan.", "Discipline +1", "If it's not scheduled, it's not real."));
        missionMap.put(49, new DailyMission(49, "INSTALLATION", "Monetization Mindset", "Riset bagaimana skill ini bisa menghasilkan uang. Bukan 'bisa', tapi 'dibayar'.", "List 5 cara skill ini bisa dijual.", "Business +1", "Learn to earn, not just learn."));
        missionMap.put(50, new DailyMission(50, "INSTALLATION", "Milestone 50 Hari", "Review 50 hari perjalanan. Dari figuran menuju...?", "Celebrasi: lakukan sesuatu yang kamu sayangi.", "Momentum +5", "50 hari sudah. Lebih dari setengah jalan.", "BONUS_DAY"));
        missionMap.put(51, new DailyMission(51, "INSTALLATION", "Skill Kedua", "Mulai pelajari skill kedua dari list 'sampah' yang sudah diidentifikasi.", "Set learning goal spesifik untuk skill kedua.", "Versatility +1", "Satu skill adalah risiko. Dua skill adalah asuransi."));
        missionMap.put(52, new DailyMission(52, "INSTALLATION", "Skill Synergy", "Cari cara menggabungkan skill pertama dan kedua. 1+1=3.", "Buat 1 konsep project yang menggabungkan kedua skill.", "Innovation +1", "Innovation happens at intersection."));
        missionMap.put(53, new DailyMission(53, "INSTALLATION", "Expert Pattern Recognition", "Baca/watch expert di skill ini. Identifikasi pola yang mereka pakai.", "Catat pola tersebut. Implement di karya kamu.", "Pattern +1", "Expertise is pattern recognition."));
        missionMap.put(54, new DailyMission(54, "INSTALLATION", "Failure Experiment", "Coba sesuatu yang mungkin gagal. Tidak apa-apa jika gagal.", "Dokumentasikan pembelajaran dari failure.", "Bravery +1", "Fail fast, learn faster."));
        missionMap.put(55, new DailyMission(55, "INSTALLATION", "Teaching to Learn", "Jelaskan skill yang sedang dipelajari ke 1 orang (atau rekam video).", "Gunakan analogi sederhana.", "Communication +1", "If you can't explain it simply, you don't understand it."));
        missionMap.put(56, new DailyMission(56, "INSTALLATION", "Portfolio Entry", "Tambahkan 1 karya baru ke portfolio. Bukan draft, tapi finished work.", "Update LinkedIn atau personal website.", "Brand +1", "Portfolio adalah resume modern."));
        missionMap.put(57, new DailyMission(57, "INSTALLATION", "Market Validation", "Test apakah market butuh skill ini. Tanya 5 orang potensial.", "Catat feedback dan pattern.", "Market +1", "Build what people want, not what you think they want."));
        missionMap.put(58, new DailyMission(58, "INSTALLATION", "Cheat Sheet Creation", "Dokumentasikan apa yang sudah dipelajari. Buat cheat sheet 1 halaman.", "Share cheat sheet untuk orang lain.", "Sharing +1", "Documentation is memory."));
        missionMap.put(59, new DailyMission(59, "INSTALLATION", "Pre-Launch Prep", "Siapkan skill untuk phase launch. Apa yang sudah siap dijual?", "List 3 services/products yang bisa ditawarkan.", "Readiness +1", "Preparation meets opportunity."));
        missionMap.put(60, new DailyMission(60, "INSTALLATION", "Graduasi Fase 2", "Review semua skill yang diinstalasi di Fase 2. Kamu bukan figuran lagi.", "Celebrasi: lakukan sesuatu yang menandakan transformasi.", "Mastery +5", "60 hari instalasi selesai. Siap untuk launch.", "BONUS_DAY"));

        // FASE 3: THE MARKET LAUNCH (HARI 61-90) - Value & Profit
        missionMap.put(61, new DailyMission(61, "MARKET LAUNCH", "Proof of Work", "Buat satu karya digital (artikel/desain/kode) yang menunjukkan identitas barumu.", "Share ke publik. Bukan draft, tapi finished work.", "Portfolio +1", "Karya adalah bukti. Bukan janji."));
        missionMap.put(62, new DailyMission(62, "MARKET LAUNCH", "The Digital Stage", "Update profil profesional (LinkedIn/sosmed) dengan bahasa 'Aktor Utama'. Hapus narasi peminta-minta, ganti dengan narasi pemberi solusi.", "Bio baru: 'Saya membantu X dengan Y untuk Z'", "Brand +1", "Kamu bukan figuran. Kamu aktor utama."));
        missionMap.put(63, new DailyMission(63, "MARKET LAUNCH", "Outreach Mission", "Hubungi 3 target potensial (klien/perusahaan) untuk menawarkan nilai unik yang sudah kamu rakit selama 60 hari terakhir.", "Personal message. Bukan template.", "Sales +1", "If you don't ask, the answer is always no."));
        missionMap.put(64, new DailyMission(64, "MARKET LAUNCH", "Menghapus Narasi Peminta", "Identifikasi 1 kalimat di bio atau konten yang terdengar 'peminta-minta'.", "Ganti dengan kalimat yang menunjukkan value.", "Confidence +1", "Aktor utama tidak meminta. Aktor utama memberi."));
        missionMap.put(65, new DailyMission(65, "MARKET LAUNCH", "Testimonial Hunt", "Minta testimonial dari 1 orang yang pernah kamu bantu (meskipun kecil).", "Post testimonial di portfolio atau profil.", "Social Proof +1", "Social proof adalah mata uang kepercayaan."));
        missionMap.put(66, new DailyMission(66, "MARKET LAUNCH", "Hari Recharge", "Hari ini libur dari selling. Focus pada self-care.", "Massage, spa, atau sekadar tidur lebih lama.", "Energy +5", "You can't pour from an empty cup.", "BONUS_DAY"));
        missionMap.put(67, new DailyMission(67, "MARKET LAUNCH", "Networking dengan Intention", "Join 1 networking event (online/offline). Bukan untuk cari kerja, tapi untuk memberi value.", "Share 1 insight yang bermanfaat.", "Network +1", "Your network is your net worth."));
        missionMap.put(68, new DailyMission(68, "MARKET LAUNCH", "Case Study Publication", "Publish 1 case study dari project yang sudah dikerjakan. Tunjukkan before-after.", "Share di LinkedIn dengan detail.", "Authority +1", "Case studies build trust."));
        missionMap.put(69, new DailyMission(69, "MARKET LAUNCH", "Follow-up yang Tegas", "Follow up 3 leads yang belum respons. Bukan 'mengganggu', tapi 'mengingatkan'.", "Use different angle: value, bukan pressure.", "Persistence +1", "The fortune is in the follow-up."));
        missionMap.put(70, new DailyMission(70, "MARKET LAUNCH", "Mid-Phase Review", "Review 10 hari pertama Fase 3. Apa yang working? Apa yang tidak?", "Double down pada yang working. Kill yang tidak.", "Optimization +1", "Do more of what works."));
        missionMap.put(71, new DailyMission(71, "MARKET LAUNCH", "Referral System", "Buat sistem referral. Minta client untuk refer teman.", "Offer incentive untuk referral.", "Leverage +1", "Referrals adalah leads terbaik."));
        missionMap.put(72, new DailyMission(72, "MARKET LAUNCH", "Content Batching", "Buat 5 konten sekaligus untuk seminggu ke depan.", "Schedule posting dengan tool.", "Efficiency +1", "Batching menghemat waktu."));
        missionMap.put(73, new DailyMission(73, "MARKET LAUNCH", "Pricing dengan Percaya Diri", "Review pricing. Apakah sudah sesuai value yang kamu berikan?", "Test price increase untuk 1 client.", "Worth +1", "Pricing adalah positioning."));
        missionMap.put(74, new DailyMission(74, "MARKET LAUNCH", "Partnership Outreach", "Reach out to 1 potential partner (complementary business).", "Propose collaboration idea, bukan minta bantuan.", "Collaboration +1", "Partnerships multiply impact."));
        missionMap.put(75, new DailyMission(75, "MARKET LAUNCH", "Hari Refleksi", "Hari ini spesial. Tidak ada tugas selling.", "Baca buku tentang bisnis atau sales. Atau nonton TED talk.", "Business IQ +5", "75 hari konsisten. Kamu di final stretch.", "BONUS_DAY"));
        missionMap.put(76, new DailyMission(76, "MARKET LAUNCH", "Email List Building", "Start email list. Create lead magnet.", "Share lead magnet di social media.", "Asset +1", "Email list adalah audience yang kamu miliki."));
        missionMap.put(77, new DailyMission(77, "MARKET LAUNCH", "Video Content", "Buat 1 video content (reels/shorts/YouTube).", "Post dan engage dengan comments.", "Video +1", "Video adalah masa depan konten."));
        missionMap.put(78, new DailyMission(78, "MARKET LAUNCH", "Client Success Check", "Cek-in dengan existing client. Apakah mereka happy?", "Ask for feedback dan testimonial.", "Retention +1", "Happy clients = repeat business."));
        missionMap.put(79, new DailyMission(79, "MARKET LAUNCH", "New Offer Creation", "Buat 1 new offer (package/bundle).", "Test offer ke 5 people.", "Innovation +1", "New offers = new revenue."));
        missionMap.put(80, new DailyMission(80, "MARKET LAUNCH", "Milestone 80 Hari", "Review 80 hari journey. Tulis transformation story: dari figuran ke...", "Share story di social media.", "Reflection +5", "80 hari sudah. 10 hari lagi.", "BONUS_DAY"));
        missionMap.put(81, new DailyMission(81, "MARKET LAUNCH", "Upsell dengan Value", "Upsell 1 existing client ke higher package.", "Focus on additional value, bukan just price.", "Revenue +1", "Upselling lebih mudah dari new selling."));
        missionMap.put(82, new DailyMission(82, "MARKET LAUNCH", "Community Building", "Start community (WhatsApp group, Discord, etc).", "Invite 10 people to join.", "Community +1", "Community = loyalty."));
        missionMap.put(83, new DailyMission(83, "MARKET LAUNCH", "Automation Setup", "Automate 1 repetitive task (email, scheduling, etc).", "Use tool like Zapier atau native automation.", "Systems +1", "Automate or delegate."));
        missionMap.put(84, new DailyMission(84, "MARKET LAUNCH", "Guest Post", "Pitch 1 guest post ke publication atau blog.", "Write article tentang expertise.", "Authority +1", "Guest posts build authority."));
        missionMap.put(85, new DailyMission(85, "MARKET LAUNCH", "Testimonial Collection", "Collect 5 testimonials dari happy clients.", "Create testimonial page.", "Trust +1", "Testimonials menjual untukmu."));
        missionMap.put(86, new DailyMission(86, "MARKET LAUNCH", "Funnel Optimization", "Review funnel. Di mana people drop off?", "Fix 1 bottleneck.", "Conversion +1", "Optimization tidak pernah berakhir."));
        missionMap.put(87, new DailyMission(87, "MARKET LAUNCH", "Strategic Partnership", "Execute 1 partnership yang sudah di-discuss.", "Measure result dari partnership.", "Execution +1", "Partnerships accelerate growth."));
        missionMap.put(88, new DailyMission(88, "MARKET LAUNCH", "Revenue Goal Check", "Review revenue vs goal. Apakah on track?", "Adjust strategy jika perlu.", "Financial +1", "What gets measured gets managed."));
        missionMap.put(89, new DailyMission(89, "MARKET LAUNCH", "Final Push", "Do 1 big thing untuk menutup 90 hari dengan bang.", "Launch 1 campaign atau project besar.", "Impact +1", "Finish strong."));
        missionMap.put(90, new DailyMission(90, "MARKET LAUNCH", "Graduation Day", "Review seluruh 90 hari journey. Celebrate transformation.", "Plan next 90 days. Ini bukan akhir, ini awal.", "Transformation +10", "90 hari selesai. Kamu bukan orang yang sama. Dari figuran ke Aktor Utama. Selamat!", "BONUS_DAY"));
    }

    public DailyMission getMissionByDay(int day) {
        return missionMap.get(day);
    }

    public Map<Integer, DailyMission> getAllMissions() {
        return missionMap;
    }

    public int getTotalDays() {
        return missionMap.size();
    }
}
